name: Build and deploy to GitHub Pages

on:
    push:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout üõéÔ∏è
              uses: actions/checkout@v2.3.1
              env:
                  REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}

            - name: Install, lint, build üîß
              env:
                  REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
              run: |
                  npm install
                  npm run lint:js
                  npm run build

            - name: Deploy üöÄ
              uses: JamesIves/github-pages-deploy-action@4.1.0
              env:
                  REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
              with:
                  branch: gh-pages
                  folder: build
                  REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
